WORKFLOW.md

Update to the text on line 16 of the file. There was a missing '>'. Primarily added for consistent formatting.

WORKFLOW.md update

---

src/helpers/db.py
src/helpers/log.py

Expecting this to work better with Fargate logging.

Adds log.info and a flush when printing + use it in load_rules

---

run
src/alert_queries_runner.py
src/helpers/db.py
src/helpers/log.py
src/violation_queries_runner.py

Only material change is that currently, our violations runner does not recover from errors in a query. After this change, it will print error and continues onwards to the others.

Minor runner improvements + bugfix

---

.circleci/config.yml
.dockerignore
builder/Dockerfile
docs/src/pages/start.rst

- improved Jira template links to source search
- improved docs page
- various bugfixes

v1.1.0 Testing Feature Release

---

src/plugins/create_jira.py

"vars" should have been "escaped_locals_strings"

Fixes bug in linking code and makes it more readable

---

src/alert_handler.py
src/alert_queries_runner.py
src/alert_suppressions_runner.py
src/config.py
src/helpers/log.py
src/violation_queries_runner.py
src/violation_suppressions_runner.py

Two main caveats:
1. CloudWatch region is fixed to us-west-2 right now
2. CLOUDWATCH_METRICS env variable needs to be set to True

added cloudwatch metrics support for runners and handlers

---

src/scripts/list_aws_accounts.py

uploaded script for listing accounts

---

src/runners/alert_queries_runner.py

Query runner string casting

---

src/requirements.txt
src/scripts/install.py
src/setup.py

Fix security warning & installer examples

---

src/runners/alert_queries_runner.py

Fixes alert deduplication logic & grouping cutoff

---

src/runners/helpers/db.py
src/runners/helpers/dbconnect.py

Adds dbconnect override for displaying URL in command line

---

src/runners/alert_queries_runner.py
src/runners/helpers/log.py
src/runners/run.py

Fix logging errors

---

src/samui/backend/samui/api/__init__.py
src/samui/frontend/src/actions/rules.ts
src/samui/frontend/src/api.ts
src/samui/frontend/src/components/RuleEditors/FormEditor.tsx
src/samui/frontend/src/components/RuleEditors/RawEditor.tsx
src/samui/frontend/src/reducers/rules.ts

Now able to seamlessly delete rules in SAMUI

Samui rule deletion

---

.gitignore
src/runners/alert_queries_runner.py
src/runners/utils.py

Fixes "max number of expressions" error

---

src/runners/helpers/db.py

going to test in our own deploy overnight, so thinking through how this might break sans running might save us lots of time

Fixes reconnect in case of expired auth token

---

src/scripts/install.py

- url parsing bug & method name clarified
- fixed import error
- create both metadata tables

Fixes installer bugs & quirks

---

src/runners/alert_handler.py
src/runners/alert_queries_runner.py
src/runners/alert_suppressions_runner.py
src/runners/helpers/db.py
src/runners/violation_suppressions_runner.py

not yet tested.
more refactoring may be worthwhile, to e.g. abstract the `INSERT` statements a bit.

Changes most fatal logs to error logs

---

src/runners/helpers/auth.py
src/runners/helpers/db.py
src/runners/helpers/dbconfig.py
src/runners/helpers/dbconnect.py
src/samui/backend/samui/api/__init__.py
src/samui/backend/samui/api/oauth.py
src/samui/backend/samui/app.py
src/samui/frontend/src/actions/auth.ts
src/samui/frontend/src/actions/rules.ts
src/samui/frontend/src/api.ts
src/samui/frontend/src/common/router.ts
src/samui/frontend/src/components/GlobalHeader/GlobalHeader.styl
src/samui/frontend/src/components/GlobalHeader/GlobalHeader.tsx
src/samui/frontend/src/components/RulesTree/RulesTree.tsx
src/samui/frontend/src/constants/routes.ts
src/samui/frontend/src/layouts/MainLayout.tsx
src/samui/frontend/src/routes/User/Login.styl
src/samui/frontend/src/routes/User/Login.tsx

Initial implementation of OAuth

---

docs/src/pages/start.rst
src/runners/helpers/db.py
src/runners/helpers/log.py
src/runners/violation_queries_runner.py
src/samui/frontend/src/api.ts

Adds helpful logging, a minor OAuth fix, and updates documentation to include mention of SAMUI.

Release v1.5.0

---

src/runners/helpers/db.py
src/runners/violation_queries_runner.py
src/samui/frontend/src/actions/rules.ts
src/samui/frontend/src/components/Dashboard/RuleDashboard.tsx
src/samui/frontend/src/components/RuleEditors/QueryEditor.styl
src/samui/frontend/src/components/RuleEditors/QueryEditor.tsx
src/samui/frontend/src/components/RuleEditors/RawEditor.tsx
src/samui/frontend/src/components/RuleEditors/index.ts
src/samui/frontend/src/components/RulesTree/RulesTree.tsx
src/samui/frontend/src/reducers/rules.ts
src/samui/frontend/src/reducers/types.ts
src/samui/frontend/src/routes/Dashboard/Alerts.tsx
src/samui/frontend/src/routes/Dashboard/Violations.tsx
src/samui/frontend/src/store/rules.ts
src/scripts/install.py

- tags to narrow down your queries
- tag list to filter your tags
- various fixes to editors and runners

v1.5.2 Tag List and various fixes

---

src/runners/run.py

Extremely minor bugfix to run.py

minor bugfix to run.py for ingestion

---

src/baseline_modules/summary_stats/summary_stats.R

Add Summary Stats module to baseline_modules

---

src/baseline_modules/summary_stats/summary_stats.R

Updated return table name so the pandas gets something to process

Updated the return table name to match login module

---

src/samui/backend/samui/app.py

Improves WebUI caching logic

---

src/ingestion/ec2_describe_instances.py
src/ingestion/iam_credential_report.py
src/ingestion/list_aws_accounts.py

Also renamed env vars for more common use friendliness

Add ingest for ec2 describe instances and iam credential reports

---

src/ingestion/ec2_describe_instances.py
src/ingestion/iam_credential_report.py

switch iam reports to batch load to snowflake as well
switches group creator to use utils.groups_of
list flattening switched to comprehension

 switch aws account id from int to str to preserve leading zeroes

---

src/ingestion/zengrc.py
src/runners/helpers/db.py

To test: Add the environment variables defined at the top of the file, then run `python zengrc.py`.
Code was tested in our DEV environment and confirmed that data ingests when scheduled, and file exits cleanly when ingestion is not scheduled.

Add ZenGRC Ingestion Script

---

src/ingestion/zengrc.py
src/runners/helpers/auth.py
src/runners/helpers/db.py
src/runners/helpers/kms.py
src/scripts/install.py

- fixes a bug in runners unable to decrypt pk passphrase
- fixes a bug in installer crashing when unable to find samples share
- adds ZenGRC Ingestion Script

v1.7.1 Follow up

---

src/ingestion/ec2_describe_instances.py
src/ingestion/iam_credential_report.py

and also ensure all inserts have the same timestamp per run

improve logging and fix ec2 describe instances not recording all regions

---

src/ingestion/agari.py

Code was tested in Dev and runs with no issues

Adds detailed information to agari messages with trust score <= 5.0

---

src/ingestion/azure_ingest.py
src/runners/helpers/auth.py
src/runners/helpers/db.py
src/setup.py

Collects logs from a blob in a storage account and ingests them to Snowflake. Tested.

Azure ingest

---

src/connectors/__init__.py
src/connectors/azure_log.py
src/connectors/okta.py
src/mypy.ini

Tested with dev subscription in dev Snowflake account. Connected three different Azure Log types (AD Audit, AD Signin, and Operation) using the WebUI, then ran the ingest runner locally (using the SA_ROLE) to test ingestion and verify that permissions are properly set.

Azure Log Connector

---

src/ingestion/aad_auditlogs.py

updating graph api to 1.0

---

src/scripts/find_dependencies_in_tables.R
src/scripts/test.R

Blast radius script

---

src/baseline_modules/violations_closeout_date/violations_closeout_date.R
src/baseline_modules/violations_linear_prediction/violations_linear_prediction.R

Two modules around violations. 
They are nearly the same code, but without Greg Im not going to try to combine them.
The first gives expected predicted values for number of violations 100 days in the future - there is no control for negative violations right now(hello v0), so they are permitted and possible. 
The second gives the expected number when the violations go to zero.

Linear prediction violations

---

src/baseline_modules/violations_closeout_date/violations_closeout_date.R

Added print statements, removed suppression for libraries

---

src/runners/handlers/slack.py
src/runners/helpers/db.py

Fixes Slack handler escaped chars errors

---

src/runners/tests/regression/SP1288_snowflake_url_parsing.py
src/scripts/install.py

* Tested via runners/tests/regression/SP1288_snowflake_url_parsing.py

[Installer] Adds support for Azure URL Parsing

---

src/baseline_modules/temporal_by_day/temporal_by_day.R

converts temporal baseline to use both averages and raw events based on user input in configs

converts temporal baseline to use both averages and raw events

---

src/connectors/aws_config.py
src/runners/helpers/db.py

tested & fixed by @greg-snowflake that it works in dev

Fixes AWS Config setup by removing backfill

---

migrations/v1_8_4-v1_8_5.md
src/connectors/okta.py

Tested by running the webui locally and creating the connection in a dev environment, verifying that all tables are populated correctly.

[DC] Okta Connector Enhancement

---

migrations/v1_8_5-v1_8_6.md
src/connectors/cisco_umbrella.py

[DC] Changed Cisco Umbrella Table Name

---

src/runners/connectors_runner.py

* Connection Runner can run single tables again

[BUGFIX] Connection Runner

---

src/requirements.txt

Seems like I broke the build, this should fix it.

Add pybrake to requirements.txt

---

src/runners/alert_queries_runner.py
src/runners/handlers/jira.py
src/webui/frontend/yarn.lock

- Making grouping cutoff time configurable via environment variable while keeping backwards compatible
- Adding support for JIRA custom field "Area"

Make cutoff time configurable and add support for a JIRA custom field

---

src/connectors/aws_inventory.py

[DC] AWS AMI Inventory

---

packs/Snowflake_Security_Monitoring

Create Snowflake_Security_Monitoring pack

---

docs/connectors/salesforce_event_log.md

This PR adds documentation for the Salesforce Event Log collector prerequisites.

Documentation for Salesforce Event Log collector

---

src/runners/helpers/db.py
src/runners/helpers/dbconfig.py
src/scripts/install.py

Folks are running this against non-standard deployments and seems it's relatively easy to support the use-case. Tested as working on local deployment.

[misc] Adds optional port envar for local tests

---

packs/cis_azure_pack.sql
src/connectors/azure_collect.py

Tested by running queries against our collected data, double checking nothing seemed too surprising.

Azure CIS 2.1 to 3.8

---

packs/cis_azure_pack.sql

CIS 7.1 OS Disk must be encrypted
CIS 7.2 Data Disks must be encrypted

AZ CIS 7.1, 7.2

---

packs/cis_azure_pack.sql

Testing by running the queries as I go along and making sure results match what is expected.
[wip] means this is a work in progress -- will add TODO's in code as notes for what is left (some may stay through launch, if we can cut those corners).

Azure CIS 5 & 6

---

src/connectors/tests/test_aws_collect.py
src/runners/conftest.py

Fix unit test to use the correct key.

Fix aws collect ut

---

src/webui/frontend/package.json
src/webui/frontend/src/api.ts
src/webui/frontend/src/registerServiceWorker.ts

manual review -- all changes immaterial to code

Run new version of Prettify on all ts, tsx

---

src/webui/frontend/package.json
src/webui/frontend/src/actions/auth.ts
src/webui/frontend/src/common/menu.ts
src/webui/frontend/src/common/router.ts
src/webui/frontend/src/components/EditableTagGroup.tsx
src/webui/frontend/src/layouts/BasicLayout.tsx
src/webui/frontend/src/reducers/data.ts
src/webui/frontend/src/reducers/rules.ts
src/webui/frontend/src/reducers/types.ts
src/webui/frontend/src/store/rules.ts

- Fix `lint-all` command
- Run prettier 2.1.2 on all `ts, tsx` files

Fix prettier lint-all and run prettier on all directories.

---

src/webui/frontend/package.json
src/webui/frontend/src/components/Dashboard/RuleDashboard.tsx
src/webui/frontend/src/components/GlobalFooter/GlobalFooter.tsx
src/webui/frontend/src/components/GlobalHeader/GlobalHeader.tsx
src/webui/frontend/src/components/HeaderSearch/HeaderSearch.tsx
src/webui/frontend/src/components/RuleEditors/QueryEditor.tsx
src/webui/frontend/src/components/RuleEditors/RawEditor.tsx
src/webui/frontend/src/components/RulesTree/RulesTree.tsx
src/webui/frontend/src/components/SiderMenu/SiderMenu.tsx
src/webui/frontend/src/routes/Dashboard/Alerts.tsx
src/webui/frontend/src/routes/Dashboard/Baselines.tsx
src/webui/frontend/src/routes/Dashboard/Policies.tsx
src/webui/frontend/src/routes/Dashboard/Violations.tsx
src/webui/frontend/src/routes/User/Login.tsx

- Small fix to `lint-all` script to add double-quotes around the directory path
- Prettier fix to more directories that were missed by the previous command
Testing:
Ran `yarn run list-all`

Run prettier on all again

---

Dockerfile.snowalert
packs/aws_query_pack.sql

* Match GRANT SELECT statement to created rule above it to match convention.
* ~remove cloudtrail.deployment as it is not referenced in [aws_cloudtrail.py](https://github.com/snowflakedb/SnowAlert/blob/v1.9.6/src/connectors/aws_cloudtrail.py) when creating new tables.~

update aws_query_pack to match GRANT statement

---

src/webui/frontend/package.json
src/webui/frontend/src/components/RuleEditors/QueryEditor.tsx
src/webui/frontend/src/components/RuleEditors/RawEditor.tsx
src/webui/frontend/yarn.lock

Add format button on RawEditor

---

PULL_REQUEST_TEMPLATE.md

**Changes:**
Add PR template to root directory
**Tests:**
No logical changes to test.

add PR template

---

Dockerfile.snowalert
src/runners/handlers/msteams.py
src/setup.py

This allows us to send alerts to MS Teams channels via webhooks.
If you don't know how to get the webhook for an MS Teams channel:
https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using#setting-up-a-custom-incoming-webhook
A typical handler using this new 'msteams' handler would look like the following:
```
ARRAY_CONSTRUCT(
OBJECT_CONSTRUCT(
'type', 'msteams',
'webhook', 'https://outlook.office.com/webhook/xxxxxx/IncomingWebhook/xxxxx/xxxxx',
'title', 'Resource created in Snowflake.',
'color', '#FF0000',
'message', 'This is a test alert; the actor is ' || actor || ' and the action is ' || action || '.'
)
)
```

Adding handler for MS Teams

---

src/webui/frontend/package.json
src/webui/frontend/src/components/RuleEditors/RawEditor.tsx
src/webui/frontend/yarn.lock

**Changes**:
- Modify sql formatter library to use `snowsql-formatter`
**Tests**:
Tested UI `Format` button on Dev and it works.

Change dependency to snowsql-formatter

---

migrations/v1_9_6-v1_10_0.md
src/connectors/aws_collect.py

ran it locally and made sure data populated in snowflake appropriately

[DC] Add S3 Get Bucket Tagging

---

src/connectors/h1_collect.py

**_Changes_**:
- Add paginated inserts for reports and transactions
- Change prompt to add context to the URL
- Modified PAGE_SIZE to 100
**_Tests_**:
- Tested in dev and found that records were inserted successfully
- tested with a page size of 1 and it correctly inserted 1 record per page for a total of 2 records

Add pagination h1 collect

---

Dockerfile.snowalert
src/connectors/h1_collect.py

**_Changes_**
- Update year to 2012

H1 fix transactions

---

src/connectors/google_collect.py

ran against gcloud sandbox + snowhouse, verified results are landing in `data.google_collect_connection`

Google Collect Connector

---

src/connectors/google_collect.py

- Add groups
- Add members as child resource to groups

Add groups and members query

---

src/runners/alert_processor.py
src/runners/tests/run_alerts.py

We ran into an error in correlation logic. This change migrates us to the SQL code from the "Task Based Runners" branch which works to satisfy a test mimicking the correlation logic we had.

[processor] Fix correlation logic on lists

---

src/connectors/google_collect.py
src/connectors/utils.py

runs without error and ingests rows as expected

[dc] Add SCC Findings to GCPIC

---

Dockerfile.snowalert
src/connectors/okta.py

Default was 1000
https://developer.okta.com/docs/reference/api/groups/#list-group-members
Based syntax on that - I think I did it right but haven't gotten all the tokens setup to see

increase limit when populating users in an okta group

---

src/connectors/okta.py

Reverts snowflakedb/SnowAlert#473

Revert "increase limit when populating users in an okta group"

---

src/runners/handlers/jira.py

written very carefully and re-read twice

Add Jira list values in custom fields

---

.circleci/config.yml
infra/terraform/external_function/snowalert/lambda-code/drivers/process_https.py
infra/terraform/external_function/snowalert/lambda-code/drivers/process_smtp.py
infra/terraform/external_function/snowalert/lambda-code/lambda_function.py
infra/terraform/external_function/snowalert/lambda-code/requirements-dev.txt
infra/terraform/external_function/snowalert/lambda-code/requirements.txt
infra/terraform/external_function/snowalert/lambda-code/test.py
infra/terraform/external_function/snowalert/lambda-code/utils.py
infra/terraform/external_function/snowalert/lambda-code/vault.py

- Made changes to the https driver to add cursor capabilities for pagination
- Added two tests

Modify https driver

---

.circleci/config.yml
src/runners/utils.py

works locally and circleci [passes](https://app.circleci.com/pipelines/github/snowflakedb/SnowAlert/690/workflows/cd6b2c85-7a15-42e0-bd04-36f87d805700/jobs/4997)

Fix new mypy errors

---

migrations/v1_9_6-v1_10_0.md
src/connectors/aws_collect.py

This has not been tested and was written based off pattern matching on previous examples within the files.

[Fix] Collecting IAM managed/inline policy data for users/groups/roles

---

src/runners/helpers/db.py
src/runners/tests/run_violations.py

checked [automated tests](https://app.circleci.com/pipelines/github/snowflakedb/SnowAlert?branch=record_alert_query_id)

Return query id from AQR error exceptions

---

src/webui/frontend/package.json
src/webui/frontend/src/actions/auth.ts
src/webui/frontend/src/actions/data.ts
src/webui/frontend/src/actions/rules.ts
src/webui/frontend/yarn.lock

Installed dependencies, built and ran the WebUI to confirm that there are no breaking changes.

Update WebUI dependencies

---

src/mypy.ini
src/runners/helpers/db.py
src/runners/utils.py
src/setup.py

Snowflake sometimes returns an "undefined" value inside of arrays created by SQL expression CREATE_ARRAY(NULL). This fixes it by using the process described in https://skeptric.com/demjson/
Tested by pasting new code into ipython and running formerly invalid value through `load_js_object(x)` to make sure it parsed and running automated tests.

[fix] Fix parsing of "undefined" in VARIANT results

---

src/runners/helpers/db.py

Fix broken demjson reference

---

src/runners/alert_dispatcher.py

automated tests and mypy passing

Ignore ef handlers

---

migrations/v1_9_6-v1_10_0.md
src/connectors/azure_collect.py

tested locally, evidence in [GSE-3856](https://snowflakecomputing.atlassian.net/browse/GSE-3856) "AzIC VM data quality errors, new pricings key"
[GSE-3856]: https://snowflakecomputing.atlassian.net/browse/GSE-3856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add raw column to azure_collect_pricings

---

Dockerfile.snowalert

Reverts snowflakedb/SnowAlert#665

Revert "Update base image to Python 3.8 on Debian bookworm"

---

src/connectors/aws_collect.py
src/connectors/utils.py
src/setup.py

Reverts snowflakedb/SnowAlert#664

Revert "GSE-3635: Fix AWSIC logging and status=408 errors"

---

src/connectors/aws_collect.py
src/connectors/utils.py
src/setup.py

the build was broken by change to a "slimming" of Debian slim, and fixed by the update to `python:3.9-slim-bookworm` with the latest `snowflake-connector-python` in #670, and this code should be good per testing in #664

Reapply "GSE-3635: Fix AWSIC logging and status=408 errors (#664)"

---

migrations/v1_9_6-v1_10_0.md
src/connectors/azure_collect.py

https://snowflakecomputing.atlassian.net/browse/GSE-4150

[GSE-4150] Update azure_collect.py to fix `KeyError: 'managedByExtended'` error
