src/plugins/create_jira.py
1 escape_jira_strings escapes '{' in sets and '[' in lists
- before, it would only do so in strings (e.g. Event Data)
2 jira_ticket_body links "Sources" value to a search for other tickets
- PoC. might be useful in other places, as well
=> Adds minor fixes in create_jira module

src/config.py, src/helpers/auth.py, src/helpers/db.py, src/scripts/install.py
To test, ran with oz creds —
```c = db.connect()
db.preflight_checks(c)
```
in Python console and noted that no errors occurred. Also, ran the commands inside preflight_checks and made sure their results are as-expected, specifically:
```
In [77]: user_props = dict((x['property'], x['value']) for x in fetch(ctx, f'DESC USER {config.USER};'))
In [78]: user_props
Out[78]:
{'NAME': 'SNOWALERT',
'COMMENT': 'null',
'LOGIN_NAME': 'SNOWALERT',
'DISPLAY_NAME': 'SNOWALERT',
'FIRST_NAME': 'null',
'MIDDLE_NAME': 'null',
'LAST_NAME': 'null',
'EMAIL': 'null',
'PASSWORD': '********',
'MUST_CHANGE_PASSWORD': 'false',
'DISABLED': 'false',
'SNOWFLAKE_LOCK': 'false',
'SNOWFLAKE_SUPPORT': 'false',
'DAYS_TO_EXPIRY': 'null',
'MINS_TO_UNLOCK': 'null',
'DEFAULT_WAREHOUSE': 'SNOWALERT',
'DEFAULT_NAMESPACE': …
```
=> Adds preflight check on db connections and user defaults to installer

src/samui/backend/samui/api/__init__.py, src/samui/frontend/src/actions/rules.ts, src/samui/frontend/src/components/RuleEditors/RawEditor.styl, src/samui/frontend/src/components/RuleEditors/RawEditor.tsx, src/samui/frontend/src/components/RuleEditors/index.ts, src/samui/frontend/src/components/RulesTree/RulesTree.tsx, src/samui/frontend/src/reducers/rules.ts, src/samui/frontend/src/reducers/types.ts, src/samui/frontend/src/routes/Dashboard/Alerts.tsx, src/samui/frontend/src/routes/Dashboard/Violations.tsx
- removed `.toUpperCase` from JS so constants on client are all-caps
- standardize on errors from server
- remove some of the string-encoding hacks requiring `.split('-')[0]`
- semantic consistency
- views have names
- rules have titles, targets, types
=> Adds apply and revert buttons and a variety of minor cleanups

packs/umbrella_query_pack.sql, src/scripts/install.py
tested locally:
This is the installer for SnowAlert; it will set up all of the resources needed for SnowAlert to run.
Loaded from ~/.snowcli/config: account [...]
Next, authenticate installer with user who has 'accountadmin' role in your Snowflake account
Loaded from ~/.snowcli/config: username [...]
Loaded from ~/.snowcli/config: password [...]
Authenticating to Snowflake.. ✓
Use role accountadmin... ✓
Creating and setting default warehouse... ✓
Creating database... ✓
Creating schemas..... ✓
Creating alerts & violations tables.... ✓
Creating standard UDTFs...... ✓
[...]
and then checked UI —
query pack tested & created SAD-10783
=> Adds standard UDTFs as part of installation & c2_activity pack

src/runners/alert_queries_runner.py, src/runners/helpers/db.py
impact here is that only 16k are created at a time, and the rest are delayed until the next run. definitely worth fixing, but unlikely to impact SLA so perhaps can wait until next sprint.
not yet tested.
=> Fixes bug when more than 16k alerts need to be inserted

src/scripts/installer-queries/create-udtfs.sql.fmt
install.py already grants usage on all functions in the data schema to the role, so adding the function definition should be sufficient.
=> adds has_no_violations udtf to create-udtfs.sql.fmt

src/scripts/install.py, src/scripts/installer-queries/sample-data-queries.sql.fmt
There is no official standard for the name of the SAMPLE DATA shared db in a Snowflake account (it could be SNOWFLAKE_SAMPLE_DATA, SF_SAMPLE_DATA, SAMPLE_DATA, etc). This fix utilizes the "SHOW SHARES" command with a wildcard pattern to auto-discover the shared db name. Also, updated one of the "sql.fmt" files to have a placeholder for the shared database name ({SNOWFLAKE_SAMPLE_DATA}). This required the addition of a new optional parameter in the "read_queries()" method.
=> Dynamically discover SAMPLE_DATA shared db name

docs/src/pages/start.rst
There was a typo indicating /.showcli which should have been ~/.snowsql.
=> Updating the KMS install portion for a typo

docs/src/pages/k8s.rst, infra/k8s/manifests/sa-runner-cronjob.yaml, infra/k8s/manifests/sa-secrets.yaml, infra/k8s/manifests/sa-ui-deployment.yaml, infra/k8s/manifests/sa-ui-service.yaml
This PR adds k8s manifests for secrets, the runner, and the web ui, with an associated service.
I wrote RST documentation, but did not link it up to the index to avoid any possible merge conflicts. 
Let me know if you need any other information!
Also let me know if you are ok with the structure of `infra`
=> SA-k8sDeploy: Adding k8s manifests and docs

src/ingestion/ec2_describe_instances.py
Changes the time check to pass if snapshot data is one hour old as opposed to one day old.
=> SP-1253: ec2 snapshots get exported once an hour instead of once a day

.gitignore, src/runners/connectors_runner.py, src/runners/ingest_runner.py, src/runners/run.py
This PR separates the ingest into 2 separate runners for clarity, and then adds the `connectors` parameter to only process the data connector ingest. 
To preserve current behavior `ingest` will process the data as before (i.e. going through the `/ingestion` dir and then processing connectors). This can be removed in the future, if desired.
Additionally it adds venv to the gitignore as I know that pycharm loves to call the built in virtualenv `venv` vs `.venv`
=> Seperating Ingest and Connector logic

src/ingestion/ec2_describe_instances.py, src/runners/helpers/db.py
This is not a perfect solution, but it ingests a collection of data (account id, account alias, number of instances, or an error) to snowflake (and since it's in a try/catch block, if the insert fails for any reason it doesn't kill the rest of the ingest process).
I'd do more refactoring of the script itself (e.g. to use the db functions instead of constructing raw sql) but this script will be obsoleted with a connector soon and it doesn't seem like a productive use of time to fix this up more than this.
=> collects aws account information to snowflake

src/runners/handlers/jira.py
Tested in dev account by creating an alert with the following handler defined:
```
, ARRAY_CONSTRUCT(
OBJECT_CONSTRUCT(
'type', 'jira',
'project', 'FOO'
)
) AS handlers
```
And verified that the ticket was sent to the FOO project as opposed to the project defined in the environment variables. Additionally, tested a ticket with no defined handler and verified that it was sent to the environment-defined project as normal.
=> Jira project

migrations/v1_8_1-v1_8_2.md, src/connectors/aws_config.py
tested in dev by running the UI locally and creating the connector, hooking it up to an S3 bucket in a sandbox account, and manually uploading config snapshots to the s3 bucket
=> Records timestamp of snapshot creation as event_time

src/connectors/aws_cloudtrail.py
ModuleNotFoundError: No module named 'connectors.cloudtrail'
=> Rename the Cloudtrail comment to aws_cloudtrail

src/connectors/aws_inventory.py
Was confusing before what this entailed and had to look at the source code to see exactly what it was used for. I think it would be more clear if you just asked for the whole table name because then the user would then know that table must exist in order for the inventory table to be created.
=> Change AWS Inventory Connection Identifier Name

src/requirements.txt, src/setup.py
Snowflake support suggested I upgrade client version to latest. This seems to help with the JWT invalid token issue somewhat.
=> Upgrade snowflake-connector-python to 1.9.0

src/connectors/okta.py
Tested and was able to see `DEPROVISIONED` users in Okta users table.
ran `python runners/connectors_runners.py --connection_table="OKTA_CZI_DUO_USERS_CONNECTION"` and was able to see the correct results in Snowflake.
=> Added Deprovisioned Users to All Users

src/runners/connectors_runner.py
Allows for quicker local testing of connectors. Tested by running
`python runners/connectors_runner.py --connection-table="OKTA_%"`
=> Add fire library to connectors_runner.py

src/connectors/aws_cloudtrail.py
We are getting some values of 'unavailable' for our `value:userIdentity.sessionContext.attributes.mfaAuthenticated` column which is creating an error. TYPE_CAST helps prevent an error from occurring and replaces value with `NULL` if the TYPE_CAST doesn't recognize value.
=> Cloudtrail Try Cast Boolean Value for MFA

src/connectors/assetpanda.py
The max pagesize supported at the API is only 50 records. Using a pagesize any higher will skip records as an offset is used.
=> Fix AssetPanda paging

infra/cfn/CLOUDFORMATION.md, infra/cfn/snowalert.yaml
This PR adds a pure CloudFormation option for infrastructure deployment.
It is based on the existing k8s/terraform templates, but:
- includes all resource in the one template, including the KMS key
- the WebUI is optional, controlled by a parameter
- Fargate containers retrieve their configuration via SSM parameters
If included, the Web UI includes an HTTPS Application Load Balancer (certificates are free via ACM) and Route53 records.
=> Cloudformation template

migrations/v1_9_0-v1_9_1.md, src/connectors/aws_collect.py, src/connectors/tests/test_aws_collect.py, src/connectors/utils.py, src/mypy.ini, src/pytest.ini, src/runners/helpers/db.py, src/setup.py, src/webui/backend/webui/app.py
Tested by running to completion in about ~14 hours for us, at about 21 requests per hour. There's more optimization to be had, but this is a start to make it feasible in our org.
It also includes fixes to the tables to match the documented API schema rather than using samples from our APIs.
=> Bug fixes and speed optimizations in AWS Collection Connector

Dockerfile.webui, docs/src/pages/authentication.rst, docs/src/pages/start.rst, infra/cfn/CLOUDFORMATION.md, infra/cfn/snowalert.yaml, migrations/v1_9_0-v1_9_1.md, src/connectors/airwatch_devices.py, src/connectors/aws_collect.py, src/connectors/tests/test_aws_collect.py, src/connectors/utils.py, src/mypy.ini, src/pytest.ini, src/runners/helpers/db.py, src/runners/helpers/dbconfig.py, src/runners/tests/run_alerts.py, src/scripts/installer-queries/create-udtfs.sql.fmt, src/setup.py, src/webui/backend/webui/api/data.py, src/webui/backend/webui/app.py, src/webui/frontend/src/actions/rules.ts, src/webui/frontend/src/components/GlobalHeader/GlobalHeader.tsx, src/webui/frontend/src/reducers/data.ts, src/webui/frontend/src/reducers/rules.ts
- CloudFormation Templates are now included in `./infra/cfn` (#362)
Thank you @maestro-jamesweakley (aka @jamesweakley) for contributing this to the release!
The AWS Collection Connector has gotten a performance and reliability boost, designed to handle collection for even the largest organizations.
- AWS Collector has more accurate table name (efac7a6)
- AWS Collection bug fixes & speed optimizations (#363)
- AWS Collector iterates over all regions (7760e2d)
The WebUI is moving out of a "work in progress" and into a "designed for production" state.
- Adds redirect-to-login fallback on auth errors in WebUI (3fe911e)
- Fixes server crash on invalid OAuth tokens (eb2984e)
- Use user's default db instead of environment variable in WebUI (ce42b77)
- Fix db connection cache persisting between …
=> v1.9.1 AWS Collection and WebUI improvements

docs/src/pages/authentication.rst, src/runners/helpers/db.py, src/webui/backend/webui/api/oauth.py
This PR is in relation to issue #367.
The broad intent of this PR is to allow Snowflake users to access SnowAlert without needing to adjust their default user parameters. 
The suggestion by @andrey-snowflake in the issue would provide the most flexible solution for the user, but would only address Database and Warehouse selection. Because Role must be included in the OAuth request I don't think it could be provided as a selection.
So this backwards compatible change introduces three new optional environment variables that apply only to OAuth connections, and they allow manual setting of Role, Database and Warehouse.
It is a low effort, low risk change at the cost of flexibility - it means that to leverage this new setting, all users on the WebUI must use the same Snowflake Role, which I …
=> Allow OAuth connection parameter overrides

infra/cfn/CLOUDFORMATION.md, infra/cfn/snowalert.yaml
This PR:
- Fixes a couple of issues with the alert container in the Cloudformation template (IAM-related and the shell command)
- Moves all of the non-sensitive parameters out of SSM and into regular template parameters
- Adds support for Jira integration to the Cloudformation template
- Adds support for the new WebUI OAuth connection parameter overrides to the Cloudformation template
=> Cloudformation template fixes

src/runners/handlers/slack.py
If the JSON contains a single quote then things blow up.
=> Fix slack template selector not using params

src/runners/alert_queries_runner.py
This change adds a few small features:
1. Explicit support for an `SA_ALERT_FROM_TIME` environment variable when the user would rather specify a given range instead of an end time and cutoff period
2. Proper handling of arguments to prevent SQL injection
3. Locking the "to" time to a consistent timestamp fur the duration of the run
**1. Support for "from time"**
An example use case is for automated periodic runs while ensuring an error does not result in a missed window. For example, say the normal execution of the task is hourly and looks at alerts from the last hour. Upon successful completion of the task, it can update the `alert_from_time` to be the previous run's `alert_to_time`. If the task fails, then the old `alert_from_time` will remain, and the next run of the task will include …
=> add explicit 'from time' argument; defend from SQL injection

src/connectors/aws_cloudtrail.py
I've fixed a bug in the timestamps on the event_time column in the AWS CloudTrail logs.  
**Finding the bug:**
I noticed the bug by running this query on the CloudTrail logs:
```
SELECT CURRENT_TIMESTAMP, MAX(EVENT_TIME) AS MAX_EVENT_TIME
FROM DATA.AWS_CLOUDTRAIL_DEFAULT_EVENTS_CONNECTION;
```
The result of the query was:
As can be seen in the query result, the latest event_time value is later than the current time, and both are marked as in the same timezone (-0700).  No events could be logging that occurred in the future, so something had to be wrong with the timezones.
**Fixing the bug:**
I suspected that the casting of the timestamp to the local time zone in the existing code was introducing the bug.  I tested this using a raw event time value as input with this query, which contains …
=> fix timezones in cloudtrail event_time column

src/runners/handlers/jira.py
When a ticket exists and is in a non-starting status, we want to create a new ticket, not simply return the last ticket.
=> [dc] Fix Jira handler correlation logic

migrations/v1_9_6-v1_10_0.md, src/connectors/aws_collect.py, src/connectors/tests/test_aws_collect.py
Fixes https://github.com/snowflakedb/SnowAlert/issues/453
Tested by:
- running the migration sql script
- running `python runners/connectors_runner.py "AWS_COLLECT_%%"` locally (under snowalert snowflake role)
- `select * from data.aws_collect_s3_get_public_access_block;` 
One thing to note is that we'll get 404's and a corresponding `ClientError` for buckets with no public access block.
=> [DC] Add aws_collect s3.get_public_access_block

src/webui/frontend/src/components/RuleEditors/RawEditor.tsx
**Changes**:
Fixed logic for `disabled=` property of format button as long as code is non-empty
**Tests**:
Ran the WebUI in dev
=> Fix format button to activate if code is not empty

src/runners/handlers/slack.py
Slack Group Messages
case 1: When single recipient_email is passed i.e direct message:
Output:
Explaination:
Here, for Single Email, string will be be passed as recipient so, convert it into list.
if isinstance(recipient_email, str):
recipient_email = [recipient_email]
case 2: When more than one recipient_email is passed i.e group slack creation:
Output:
Explaination:
If we get a list of emails, we need to iterate and get userId for each email and store it in as a list and then send all the ids as string by calling an API.
for email in recipient_email:
response = sc.api_call("users.lookupByEmail", email=email)
if not response['ok']:
log.error(f'Cannot identify Slack user for email {email}')
continue
users.append(response['user']['id'])
user_ids = ",".join(users)                  
result = …
=> Slack Group Message

src/connectors/aws_collect.py
when passed in the command line, parameters were automatically parsed into a list of integers. instead, we want to treat it as a list of strings.
=> [awsic] fix oids param, options

src/webui/frontend/package.json, src/webui/frontend/yarn.lock
Used yarn's resolutions to fix vulnerabilities present in dependencies: `nth-check` and `css-what`, by updating the parent dependency css-select to `^4.0.0`.
Bumped follow-redirects to `1.14.8`.
=> Fix remaining vulns: nth-check, css-what and follow-redirects

src/runners/alert_processor.py
Updated alert_processor to retry db.fetch, if it produces the `StopIteration` exception. 
Automated tests pass https://app.circleci.com/pipelines/github/snowflakedb/SnowAlert?branch=fix_db_fetch_exception&filter=all
=> Add retry to db.fetch in alert_processor.py

src/connectors/aws_collect.py, src/connectors/utils.py, src/setup.py
Cleans up vestigial logging (known recoverable errors are written to `error` column in the ingestion tables) and fixes the crash that originates from a 408 response and logs —
```
botocore.parsers.ResponseParserError: Unable to parse response (no element found: line 1, column 0), invalid XML received. Further retries may succeed:
b''
```
This was reproduced locally and the retry logic appears to have fixed it, verified via local run.
=> GSE-3635: Fix AWSIC logging and status=408 errors

Dockerfile.snowalert
did not run test suite, but changes are minor per [python 3.8](https://www.python.org/downloads/release/python-380/) release notes
=> Update base image to Python 3.8 on Debian bookworm

Dockerfile.snowalert
fixing error
> botocore.exceptions.CredentialRetrievalError: Error when retrieving credentials from container-role: Error retrieving metadata: Received error when attempting to retrieve container metadata: Connect timeout on endpoint URL: "http://[ip]/v2/credentials/[uuid]"
per https://repost.aws/questions/QUCFqv7OfoQlygJrmwfkJ24Q/various-aws-apis-fail-due-to-timeout
=> Update Dockerfile.snowalert to use iptables-legacy

src/connectors/aws_collect.py, src/connectors/utils.py
[GSE-3635](https://snowflakecomputing.atlassian.net/browse/GSE-3635) Fix flaky SnowAlert AWSIC data collection
main changes are:
- rate limit metadata separately but simultaneously as previous remote API pacing
- prune session cache to fix oom errors
- remove / abstract out inline retries
[GSE-3635]: https://snowflakecomputing.atlassian.net/browse/GSE-3635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix AWS Inventory & Configuration Collection
